
### Test for CKEditor content creation
POST http://localhost:3000/api/v1/note/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

editor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

### Test for CKEditor Content Upload (uploadHTMLEditor)

POST http://localhost:3000/api/v1/upload/htmlfile HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

editor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

###

### Test for Creating a New Note (createNote)

POST http://localhost:3000/api/v1/note/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

title=title1&desc=desc1&htmleditor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

### 

### Test get html content

get http://localhost:3000/api/v1/note/get/24070966-45ff-410f-b34b-3634adfc4075
Accept: application/json
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlciAzIiwiZW1haWwiOiJ1c2VyM0BleGFtcGxlLmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMzMjgyMDUxLCJleHAiOjE3MzMyODU2NTF9.e4TmIGl-uy-wHwSVnxa0mzFoWvmEzpZw-MpGyUX1Bfc

###

### Test for Page 1 (This should return no notes, since there are only 22 items in the database)
GET http://localhost:3000/api/v1/note/read/1
Accept: application/json
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlciAzIiwiZW1haWwiOiJ1c2VyM0BleGFtcGxlLmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMzMzA4NTAyLCJleHAiOjE3MzMzMTIxMDJ9.sRxw4nd26CRAf7v3qDA4bw8-zlMVpkbN5hE4AVgCDAI

### Search note test
### Tìm kiếm theo tiêu đề (title)
GET http://localhost:3000/api/v1/note/search/title/aa
Accept: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlciAzIiwiZW1haWwiOiJ1c2VyM0BleGFtcGxlLmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMzMjgyMDUxLCJleHAiOjE3MzMyODU2NTF9.e4TmIGl-uy-wHwSVnxa0mzFoWvmEzpZw-MpGyUX1Bfc

### Test Route: Search Notes by Value on All Fields
# 1. Test searching for "aaa" across all title and description fields
GET http://localhost:3000/api/v1/note/search/aaa HTTP/1.1
Accept: application/json
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlciAzIiwiZW1haWwiOiJ1c2VyM0BleGFtcGxlLmNvbSIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMzMzA4NTAyLCJleHAiOjE3MzMzMTIxMDJ9.sRxw4nd26CRAf7v3qDA4bw8-zlMVpkbN5hE4AVgCDAI