
### Test for CKEditor content creation
POST http://localhost:3000/api/v1/note/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

editor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

### Test for CKEditor Content Upload (uploadHTMLEditor)

POST http://localhost:3000/api/v1/upload/htmlfile HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

editor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

###

### Test for Creating a New Note (createNote)

POST http://localhost:3000/api/v1/note/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

title=title1&desc=desc1&htmleditor=<h1>Hello World!</h1><p>This is a test content from CKEditor.</p>

### 

### Test get html content

get http://localhost:3000/api/v1/note/get/95642657-7a69-4f51-8a54-675e746706b9